version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    docker:
      - image: circleci/python:3.7-buster
    working_directory: /home/circleci/tsconvert
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci *
      - restore_cache:
          key: tsconvert-{{ .Branch }}
      - run:
          name: Install dependencies and set path
          command: |
            sudo apt-get install libgsl-dev # Needed for 3rd party sims without wheels
            pip install --user -r requirements/development.txt
            pip install twine --user
            echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
      - save_cache:
          key: tsconvert-{{ .Branch }}
          paths:
            - "/home/circleci/.local"

      - run:
          name: Run Python tests 
          command: |
            python3 -m pytest tests --cov=tsconvert --cov-report=xml --cov-branch tests
            rm .coverage

      - codecov/upload:
          token: CODECOV_TOKEN

      - run:
          name: Build Python package
          command: |
            rm -fR build
            python setup.py sdist
            python setup.py check
            python -m twine check dist/*.tar.gz
            python -m venv venv
            source venv/bin/activate 
            pip install --upgrade setuptools pip wheel
            python setup.py build_ext
            python setup.py egg_info
            python setup.py bdist_wheel
            pip install dist/*.tar.gz 

# TODO Enable when we make the docs
#       - run:
#           name: Build docs
#           command: |
#             cd docs && make
